export const site = {
    name: "Elgin Al-wafi Dauliyah",
    age: 18,
    location: "Subang, West Java Indonesia",
    othername: "elsecx",
    description:
        "I am a fullstack programmer with experience in building functional, efficient, and clean web solutions. Mastering various technologies such as TypeScript, PHP, Go, React Native, and also modern frameworks such as Laravel, Next.js, Expo Go, I am able to handle the entire development process from the frontend to the backend.",
    url: "http://localhost:3000",
    ogImage: "/og.png",
    favicon: "/favicon.ico",
    keywords: [
        "Elgin Alwafi Dauliyah",
        "Elgin Al-wafi Dauliyah",
        "Elgin Dauliyah",
        "elgin",
        "alwafey",
        "wafey",
        "wafi",
        "el",
        "gin",
        "al",
        "waf",
        "fey",
        "Fullstack Developer",
        "Backend Developer",
        "Frontend Developer",
        "Web Developer",
        "Mobile Developer",
        "Software Engineer",
        "Programmer",
        "Portfolio",
        "Tech Portfolio",
        "Developer Portfolio",
        "Projects",
    ],
};

export const contacts = {
    email: "alwafielgin@gmail.com",
    phone: "+62 823-2054-9874",
    linkedin: "https://www.linkedin.com/in/aalwf",
    github: "https://github.com/elsecx",
    instagram: "https://instagram.com/_si.alwf",
    facebook: "",
};
